#Owner:
#  tabprefix: "&0&l[&a&lOwner&0&l] &a"
#  tagprefix: "&2&lOwner &a"
Player:
  tabprefix: "&0&l[&7&lPlayer&0&l] &3"
  tagprefix: "&2&lPlayer &3"
example_group:
  header:
    - "This is an example of per-group header/footer"
  footer:
    - "applied to a group"

  # default settings for all groups, all groups will take properties from this section unless player's primary group overrides a specific setting
_DEFAULT_:
  tabprefix: "%luckperms-prefix%"
  tagprefix: "%luckperms-prefix%"
  customtabname: "%player%"
  customtagname: "%player%" # don't forget to enable unlimited nametag mode to make this one work
  tabsuffix: "%luckperms-suffix%"
  tagsuffix: "%luckperms-suffix%"

per-world:
  world:
    _DEFAULT_:
      tabprefix: " &a● &f%luckperms-prefix%"
      tagprefix: " &a● &f%luckperms-prefix%"
  world_nether:
    _DEFAULT_:
      tabprefix: " &4● &f%luckperms-prefix%"
      tagprefix: " &4● &f%luckperms-prefix%"
  world_the_end:
    _DEFAULT_:
      tabprefix: " &5● &f%luckperms-prefix%"
      tagprefix: " &5● &f%luckperms-prefix%"
